NAME= Mommy
CC= c++
CFLAGS= -Wall -Wextra -Werror -std=c++98
SRCS= src/main.cpp src/Bureaucrat.cpp
INC= -I includes/Bureaucrat.hpp

all: $(NAME)
$(NAME):
	$(CC) $(CFLAGS) $(SRCS) -o $(NAME)

clean:

	rm $(NAME)

re: clean all 